from PyQt5 import QtCore, QtGui, QtWidgets
from win32api import GetSystemMetrics

width = int(GetSystemMetrics(0) * 1.25)
height = int(GetSystemMetrics(1) * 1.18)


class Ui_Start(object):

    # List containing all the widgets of a current window, which able us to clean a window and show new things.
    list_widgets = []

    def setup_Start(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.move(width//2-400, height//2-300)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_jeu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.bouton_jouer = QtWidgets.QPushButton(self.widget)
        self.bouton_jouer.setObjectName("bouton_jouer")
        self.horizontalLayout_5.addWidget(self.bouton_jouer)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Choix_game = QtWidgets.QComboBox(self.widget)
        self.Choix_game.setObjectName("Choix_game")
        self.Choix_game.addItem("")
        self.horizontalLayout.addWidget(self.Choix_game)
        self.Ref_game = QtWidgets.QLineEdit(self.widget)
        self.Ref_game.setObjectName("Ref_game")
        self.horizontalLayout.addWidget(self.Ref_game)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.ou = QtWidgets.QLabel(self.widget)
        self.ou.setAlignment(QtCore.Qt.AlignCenter)
        self.ou.setObjectName("ou")
        self.horizontalLayout_3.addWidget(self.ou)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_3.addWidget(self.widget_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.bouton_com = QtWidgets.QPushButton(self.widget)
        self.bouton_com.setObjectName("bouton_com")
        self.horizontalLayout_4.addWidget(self.bouton_com)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout.addWidget(self.widget_10)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 10)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.bouton_menu = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_menu.setObjectName("bouton_menu")
        self.horizontalLayout_2.addWidget(self.bouton_menu)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        Ui_Start.list_widgets.append([self.centralwidget, 1])
        Ui_Start.list_widgets.append([self.verticalLayout, 2])
        Ui_Start.list_widgets.append([self.verticalLayout_2, 3])
        Ui_Start.list_widgets.append([self.verticalLayout_3, 4])
        Ui_Start.list_widgets.append([self.horizontalLayout, 5])
        Ui_Start.list_widgets.append([self.horizontalLayout_2, 6])
        Ui_Start.list_widgets.append([self.horizontalLayout_3, 7])
        Ui_Start.list_widgets.append([self.horizontalLayout_4, 8])
        Ui_Start.list_widgets.append([self.horizontalLayout_5, 9])
        Ui_Start.list_widgets.append([self.widget, 10])
        Ui_Start.list_widgets.append([self.widget_2, 11])
        Ui_Start.list_widgets.append([self.widget_3, 12])
        Ui_Start.list_widgets.append([self.widget_4, 13])
        Ui_Start.list_widgets.append([self.widget_5, 14])
        Ui_Start.list_widgets.append([self.widget_6, 15])
        Ui_Start.list_widgets.append([self.widget_7, 16])
        Ui_Start.list_widgets.append([self.widget_8, 17])
        Ui_Start.list_widgets.append([self.widget_9, 18])
        Ui_Start.list_widgets.append([self.widget_10, 19])
        Ui_Start.list_widgets.append([self.bouton_jouer, 20])
        Ui_Start.list_widgets.append([self.bouton_menu, 21])
        Ui_Start.list_widgets.append([self.bouton_com, 23])
        Ui_Start.list_widgets.append([self.ou, 24])
        Ui_Start.list_widgets.append([self.Ref_game, 25])
        Ui_Start.list_widgets.append([self.Choix_game, 26])

        self.retranslate_Start(MainWindow)
        self.Choix_game.currentTextChanged['QString'].connect(self.Ref_game.setText)  # type: ignore
        self.Ref_game.textEdited['QString'].connect(self.Ref_game.clear)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_Start(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Summon_of_the_ShadowLand"))
        self.bouton_jouer.setText(_translate("MainWindow", "Jouer"))
        self.Choix_game.setCurrentText(_translate("MainWindow", " - Select a game"))
        self.Choix_game.setItemText(0, _translate("MainWindow", " - Select a game"))
        self.ou.setText(_translate("MainWindow", "ou"))
        self.bouton_com.setText(_translate("MainWindow", "Nouvelle partie"))
        self.bouton_menu.setText(_translate("MainWindow", "Menu"))

    def fermer(self):
        for widget in Ui_Start.list_widgets:
            del widget[0]
        Ui_Start.list_widgets = []
